### ISSUE TITLE
Scan mode booster with recovery green pass

### ISSUE THREAD

**Issue by darpins** [herald-si/verificac19-sdk-php#102]
hello,
i test my recovery green pass with the scan mode booster(RSA or 3 doses) and the output is valid.
But the real output not is need test?

**Comment by DevPGS** [comment]
Hi,
some greenpass have a special tag in the signing certificate ['extensions']['extendedKeyUsage'] with values:
```
    public const OID_RECOVERY = "1.3.6.1.4.1.1847.2021.1.3";
    public const OID_ALT_RECOVERY = "1.3.6.1.4.1.0.1847.2021.1.3";
```
Those certificates (issued after a recovery post vaccine) are valid like the 3rd dose.
You can see the validation in android-sdk source code [here](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/70909c86c9de0d609a2a3d932171c332819f1117/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/model/validation/RecoveryValidationStrategy.kt#L60)

**Comment by darpins** [comment]
perfect, thanks
