### ISSUE TITLE
compatibilità con php 7.3

### ISSUE THREAD

**Issue by st4nny** [herald-si/verificac19-sdk-php#18]
Carissimi grazie per il vostro contributo.
Mi chiedevo, ci sono particolari librerie utilizzate nel progetto che necessitano di php 7.4
posto come requisito?
La vecchia versione, provata a far girare con qualche gp di test funzionava correttamente anche con php 7.3,
ora con quella attuale chiaramente non funziona poichè sono stati specificati dei tipi su alcune varibili.

Grazie

**Comment by herald-si** [comment]
Buongiorno @st4nny , grazie per la domanda.

La problematica relativa a php 7.3 è dovuta al fatto che da lunedì prossimo (6-12-2021) verrà dismesso il supporto di sicurezza da parte della comunità per questa versione ed andrà in EOL. [PHP: Supported Versions] (https://www.php.net/supported-versions.php)

Per questo motivo lo stesso è stato rimosso dai nostri server di test e non potremo più garantire il corretto funzionamento dell'sdk su php 7.3

A disposizione

**Comment by st4nny** [comment]
Grazie per la risposta,
certo conosco il ciclo di sviluppo e so che presto andrà in EOL.
Su molti server di produzione è ancora presente la 7.3 e rhel, ad esempio, continua a mantenerne il supporto, chiedevo appunto per questo perchè molti sistemisti sono conservativi su questo e mi chiedevo se ci poteva essere un vostro interessamento a riguardo.

Un saluto e buon lavoro

**Comment by DevPGS** [comment]
@st4nny , dovrebbe essere tutto compatibile con php 7.3. 
Se vuoi puoi fare un check con la branch [release/1.0.7](https://github.com/herald-si/verificac19-sdk-php/tree/release/1.0.7)

Vedendo i rilasci della libreria [spomky-labs/cbor-php](https://github.com/Spomky-Labs/cbor-php), può essere che tra qualche rilascio sarà necessario eseguire un refactor di tutto il codice per essere compatibile con php >= 8.0, in quanto dalla versione 3.0.0 le versioni precedenti di php non sono più supportate.

**Comment by st4nny** [comment]
Fatto, direi quasi tutto ok.
Una piccola proposta di fix in pull request.

Un saluto

**Comment by DevPGS** [comment]
grazie mille @st4nny .
eseguito il merge in release/1.0.7
