### ISSUE TITLE
'Invalid signature length.' exception

### ISSUE THREAD

**Issue by lumzz** [herald-si/verificac19-sdk-php#23]
Examining some certificates with country code CH we found a signature 256 bytes long and consequently they fail the 64 length check in the function ECSignature :: toAsn1.
The behavior looks different in the SDK-Android.

**Comment by herald-si** [comment]
hi,
thanks for the report.
I haven't tested a CH Green Pass and have never encountered the issue.
I have created a branch locally and I'm working on that, to support the other signature algorithm.

**Comment by herald-si** [comment]
hi @lumzz ,
i released the new version with support for CH greenpass. I did some test with a demo CH dcg, but I can't test a real CH green certificate, can you do some checking?
the branch with new code is: https://github.com/herald-si/verificac19-sdk-php/tree/feature/ps256-alg

**Comment by lumzz** [comment]
Hi,
I embed the modified version and did some tests too. They have been successful. Thank you

**Comment by DevPGS** [comment]
https://github.com/herald-si/verificac19-sdk-php/releases/tag/v1.0.8
