### ISSUE TITLE
Spomky-Labs/cbor-php version

### ISSUE THREAD

**Issue by albertovincenzi** [herald-si/verificac19-sdk-php#25]
Hi,
I saw you used a particular version of the library but seems like that it creates some issue with composer:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires herald-si/verificac19-sdk-php ^1.0.7 -> satisfiable by herald-si/verificac19-sdk-php[v1.0.7].
    - herald-si/verificac19-sdk-php v1.0.7 requires spomky-labs/cbor-php dev-string-encode-fix -> found spomky-labs/cbor-php[v1.0.0, ..., v1.1.x-dev, v2.0.0, v2.0.1, v2.0.x-dev, v2.1.x-dev, v3.0.0, v3.0.x-dev] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Is there any particular reason why version 3.0 can't be used?

**Comment by herald-si** [comment]
Hello,

the reason version 3.0 cannot be used is that it only supports php> = 8.0.

The latest version of cbor-php which supports php 7.3 is `2.0.1`, but you run into this problem https://github.com/herald-si/verificac19-sdk-php/issues/6

Version 2.1 fixes this problem, but it's only in the dev branch and doesn't have a release tag. See this for more explanation: https://github.com/Spomky-Labs/cbor-php/pull/31#issuecomment-979792266

To bypass the composer error, you need to follow the README installation and not use the packagist version with `composer require  herald-si/verificac19-sdk-php`

**Comment by albertovincenzi** [comment]
Amazing,
I will try to "gently" push the cbor-php author to make the 2.1 release :)

**Comment by mamaoi** [comment]
:( unfortunately this matter is not for everybody ! unfortunately

**Comment by DevPGS** [comment]
spomky-labs/cbor-php 2.1.0 is available this morning. 
I have already updated composer references to use this version.

the code is the same as dev-string-encode-fix. I release the new version 1.2.2 just to get the `composer require herald-si / verificac19-sdk-php` to work properly.
