### ISSUE TITLE
Certificates scheduled refresh

### ISSUE THREAD

**Issue by albertovincenzi** [herald-si/verificac19-sdk-php#32]
Hi,
I was wondering if might be useful to refactor the certificates management in a separate class which might offer a method to download/refresh certificates "on demand". Currently, if certificates don't exist or are expired, you are downloading them of the first certificate validation attempt and usually, that request takes few seconds to complete.

A useful feature to be able to call a method every 24h to refresh the certificates automatically.

What do you think about?

**Comment by DevPGS** [comment]
hi @albertovincenzi ,
sorry for the delay, but i was working on the new revoke list.

In the new version a class has been implemented for managing calls to endpoints ([Utils\EndpointService](https://github.com/herald-si/verificac19-sdk-php/blob/feature/revoke-drl/src/Utils/EndpointService.php)) . As soon as a stable version of this branch is available, it will be possible to move the certificates download management to this class.
This will be directly callable from the outside.

do you think it can be useful compared to what is described in this issue?

**Comment by albertovincenzi** [comment]
Sure, I think would be great!
As soon as I will get some time, I would like to prepare a PR which might improve some minor things.

In any case, this package is amazing. Thanks for all your efforts
