### ISSUE TITLE
helper function to return decoded certificate

### ISSUE THREAD

**Issue by marinobresciani** [herald-si/verificac19-sdk-php#35]
Hello. 
Great library. I was thinking it would be possible to add an extra function returning the decoded qr code. Basically returning $cbor['data'][- 260][1] without wrapping into a GreenPass().

Thank you in advance,
M.

**Comment by herald-si** [comment]
Hello,
sorry but with the current specification of the ministero-salute it is not possible to return data other than those already available.

see [here](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding#requisiti-minimi) for more information
