### ISSUE TITLE
Errore loop infinito

### ISSUE THREAD

**Issue by m4tt86** [herald-si/verificac19-sdk-php#67]
Ciao a tutti,
se provo ad eseguire il seguente codice di esempio:

```
require __DIR__ . '/verificac19-sdk-php/vendor/autoload.php';
use Herald\GreenPass\Utils\CertificateValidator;

$gp_string = 'HC1:6B..MIASTRINGA';
$gp_reader = new CertificateValidator($gp_string);
$gp_info = $gp_reader->getCertificateSimple();

// Mostro la struttura dell'esito validazione
echo "<pre>" . print_r($gp_info, true) . "</pre>";
```

Ricevo il seguente errore: 

```
Fatal error: Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames in /var/www/html/testgp/verificac19-sdk-php/src/Utils/EndpointService.php on line 92
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames in /var/www/html/testgp/verificac19-sdk-php/src/Utils/EndpointService.php on line 92
```

...dove sbaglio?

Grazie mille in anticipo

**Comment by DevPGS** [comment]
Ciao @m4tt86,
non sbagli nulla.
Semplicemente il ciclo ricorsivo utilizzato per il download dei certificati, come da specifiche dil ministero-salute, viene eseguito più di 256 volte, mandando in errore XDebug:
 ```
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256'
```
 
 per ovviare a questo problema puoi impostare un numero maggiore per `max_nesting_level` nelle configurazioni del debugger, come è stato fatto nel workflow per le action dei test (vedi file `.github/workflows/unit-tests-VERSION.yml`):
 https://github.com/herald-si/verificac19-sdk-php/blob/aba84d3ee0166beb1795142323c57aa0dfdcb9d7/.github/workflows/unit-tests-80.yml#L32

**Comment by m4tt86** [comment]
Perfetto!
Grazie mille. Non c'è un modo per velocizzare il controllo? L'app VerificaC19 effettua un controllo quasi immediato

**Comment by DevPGS** [comment]
Lo scarico delle liste di verifica viene effettuato ogni 24 ore.
Nel caso in cui le stesse non esistano, al primo controllo viene scaricato l'intero "pacchetto" di verifica.
Dal secondo controllo, se le stesse sono state correttamente salvate nella cartella apposita, la verifica avviene istantaneamente.

Per ulteriori informazioni puoi leggere qui: https://github.com/herald-si/verificac19-sdk-php#cache-folder

**Comment by m4tt86** [comment]
Ok ok, ho testato e funziona tutto! Grazie mille
