### ISSUE TITLE
update Verificac19.db

### ISSUE THREAD

**Issue by darpins** [herald-si/verificac19-sdk-php#68]
Ciao @herald-si ,
sto facendo gli sviluppi e osservavo la gestione delle revoche grazie al file Verificac19.db il quale si aggiorna con riferimento al file it-gov-dgc-drl-status.json.

Mi sono reso conto che se io non utilizzo l'applicazione e non aggiorno i 2 file per qualche giorno, questo mi aggiorna solo una versione successiva a quella presente nel file it-gov-dgc-drl-status.json.
Faccio un esempio:
contenuto del file it-gov-dgc-drl-status.json prima dell'update: 
{chunk":1,"version":34,"validity":"VALID","info":null}

chiamate uri in fase dell'update
https://get.dgc.gov.it/v1/dgc/drl/check?version=34
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=1
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=2
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=3
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=4
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=5
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=6
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=7
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=8
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=9
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=10
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=11
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=12
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=13
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=14
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=15
https://get.dgc.gov.it/v1/dgc/drl?version=34&chunk=16
https://get.dgc.gov.it/v1/dgc/drl/check?version=37

contenuto del file it-gov-dgc-drl-status.json dopo l'update: 
{"chunk":1,"version":37,"validity":"VALID","info":null}

Quindi sembra che il db non venga aggiornato con le versioni 35 e 36.

E' corretto così o un bug?

Grazie 
Carlo Alberto

**Comment by DevPGS** [comment]
Ciao Carlo Alberto,
sì il funzionamento è quello corretto. Come da specifiche di ministero-salute, da qualunque versione della lista di partenza, con un singolo ciclo si arriva alla destinazione.
In pratica la lista dei certificati si aggiorna tramite DIFF tra la versione attuale e l'ultima versione disponibile e non passando per le versioni intermedie.

Qui trovi la documentazione dettagliata del flusso applicativo per la gestione della lista:
https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md#flusso-applicativo

Qui, invece, puoi trovare una tabella di esempio sul funzionamento:
https://github.com/ministero-salute/it-dgc-documentation/issues/7#issuecomment-1009531752

**Comment by darpins** [comment]
perfetto 
grazie mille, chiuso l'issue
