### ISSUE TITLE
Errore Validazione Green Pass

### ISSUE THREAD

**Issue by andreaaas** [herald-si/verificac19-sdk-php#69]
Salve,
Praticamente sto provando ad utilizzare l'SDK per php, ma dopo la validazione ottengo sempre la stessa risposta. Ovvero: 

```
object(Herald\GreenPass\Utils\CertificateValidator)[46]
  private 'greenPassSimple' => 
    object(Herald\GreenPass\Model\CertificateSimple)[50]
      public 'person' => null
      public 'dateOfBirth' => null
      public 'certificateStatus' => string 'NOT_EU_DCC' (length=10)
      public 'timeStamp' => 
        object(DateTimeImmutable)[55]
          public 'date' => string '2022-01-18 16:23:42.150655' (length=26)
          public 'timezone_type' => int 3
          public 'timezone' => string 'Asia/Kolkata' (length=12)
  private 'scanMode' => string '3G'
```

Ovviamente il certificato validato con l'app VerificaC19 è valido

**Comment by DevPGS** [comment]
ciao @andreaaas ,
NOT_EU_DCC vuol dire che in qualche punto dell'applicativo è stata generata un'eccezione e non è riuscito a validare il greenpass.
Se scarichi la versione nella branch "[debug-mode](https://github.com/herald-si/verificac19-sdk-php/tree/feature/debug-mode)", esiste la possibilità di mostrare gli errori per permetterti un debug più puntuale ([qui c'è la spiegazione di come si attiva](https://github.com/herald-si/verificac19-sdk-php/tree/feature/debug-mode#debug-mode)).

**Comment by DevPGS** [comment]
Dalla prossima release, la debug mode sarà disponibile direttamente nelle versioni taggate.

**Comment by andreaaas** [comment]
Ok visualizzo gli errori:

`InvalidArgumentException Object ( [message:protected] => Cant connect to DBPDOException: could not find driver in verificac19-sdk-php/src/Utils/VerificaC19DB.php:46 Stack trace: #0 PDO->__construct() #1`

A cosa è riferito?

**Comment by DevPGS** [comment]
dalla versione 1.1.0, per essere allineati con la versione android Ministero, è stata introdotta la gestione delle DCC Revoke List che utilizza un database SQLite.
Dall'errore segnalato sembra che sul server utilizzato per i test manchi il driver relativo.

**Comment by andreaaas** [comment]
Ok ora sembra funzionare. Grazie mille
