### ISSUE TITLE
documentazione esenzione

### ISSUE THREAD

**Issue by darpins** [herald-si/verificac19-sdk-php#84]
Buongiorno,
vista l'ultima versione di verificaC19 volevo visionare il flusso documentale per il green pass esenzione.
Sul repository del ministero della salute(https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md) non mi è sembrato di vederlo. C'è qualche altro riferimento documentale a riguardo?
Saluti
Carlo Alberto

**Comment by herald-si** [comment]
ciao @darpins,
L'esenzione ha una sezione dedicata: 
https://github.com/ministero-salute/it-dgc-documentation/blob/master/EXEMPTIONS.md
più nota descritta qui per quanto riguarda la scuola:
https://github.com/ministero-salute/it-dgc-documentation/issues/10#issuecomment-1024091726

**Comment by darpins** [comment]
grazie mille
