### ISSUE TITLE
Problema scaricamento certificati

### ISSUE THREAD

**Issue by andreaaas** [herald-si/verificac19-sdk-php#89]
Buongiorno, da questa mattina non riesco più a scaricare i certificati, abilitando il debug, ricevo questo errore:
"No response was returned from website  https://get.dgc.gov.it/v1/dgc/signercertificate/update"

Attendo cortese riscontro

**Comment by DevPGS** [comment]
penso ci siano problemi a livello generale sugli endpoint per il download dei certificati del Ministero:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/118#issuecomment-1026589597
teniamo aperto l'issue per monitorare la situazione

**Comment by gmm9200** [comment]
Confermo, stesso problema.
Forse c'è un problema di sovraccarico sui server? Sul mio telefono anche VerificaC19 non riesce ad aggiornarsi.

**Comment by DevPGS** [comment]
ho eseguito un po' di test e in questo momento lo scarico di tutti i certificati/regole/drl avviene correttamente.
@gmm9200 e @andreaaas riuscite a darmi un riscontro?

**Comment by andreaaas** [comment]
Ok, a me ora funziona

**Comment by gmm9200** [comment]
Anche qua ha ripreso a funzionare, scusate la risposta tardiva, è stata una mattinata abbastanza intensa X_X
