### ISSUE TITLE
Errore Validazione Green Pass con issuer:"Department of Health Ireland"

### ISSUE THREAD

**Issue by lumzz** [herald-si/verificac19-sdk-php#93]
Questa mattina, ho avuto un errore di validazione per due Green Pass irlandesi.
Sto utilizzando la versione 1.4.1.
L'errore è dovuto ad un non corretto riconoscimento nella lettura del CBOR dei campi doseGiven e totalDoses.
Nel CBOR in questione viene utilizzato il Major Type 7. 

Qualcuno ha sperimentato una situazione simile?

**Comment by DevPGS** [comment]
ciao @lumzz ,
volevo chiederti un'ulteriore informazione:
va in errore la parte di decodifica oppure il risultato dell'esito del GP è NOT_VALID?

**Comment by lumzz** [comment]
Ciao @DevPGS 
L'errore è nel file GreenPassCovid19Checker.php, in verifyVaccinationDose.
Alla riga:

$check_other_booster = $cert->doseGiven > $cert->totalDoses || ($cert->doseGiven == $cert->totalDoses && $cert->doseGiven > 2);

doseGiven e totalDoses non sono degli interi confrontabili ma degli oggetti.

**Comment by DevPGS** [comment]
qui trovi la specifica json del greenpass alla versione 1.3.0: [europa.eu specification](https://ec.europa.eu/health/system/files/2021-06/covid-certificate_json_specification_en_0.pdf), alla pagina 7 viene richiesto in v/dn (vaccine/dose number):
> Sequence number (positive integer) of the dose given during this vaccination
> event. 1 for the first dose, 2 for the second dose etc.
> Exactly 1 (one) non-empty field MUST be provided. 

L'unica cosa che mi viene in mente  è che la versione del GP non sia 1.3.0
La puoi verificare nel json alla voce `ver`

**Comment by lumzz** [comment]
@DevPGS 
la versione che vedo in data[-260] è 1.3.0.
Ho fatto il confronto anche con un GP italiano e non vedo differenze se non nei campi dn e sd che compaiono in quello irlandese come CBOR\OtherObject\GenericObject, mentre in quello italiano sono rispettivamente 3 e 2.

**Comment by DevPGS** [comment]
Ciao @lumzz ,
hai per caso novità?
nel caso potresti provare con questo codice di test scritto sulla libreria di decodifica CBOR che non fa alcun check della parte di signature, per capire se la conversione avviene correttamente: https://github.com/Spomky-Labs/cbor-php/issues/32#issuecomment-924235177
Nel caso in cui ci fossero problemi anche con questo codice, bisognerebbe aprire un issue li, oppure capire se ci sono problemi a livello formale nei dati presenti nel certificato.

**Comment by DevPGS** [comment]
chiudo per inattività
