### ISSUE TITLE
Errore validazione tipologia WORK

### ISSUE THREAD

**Issue by fvettore** [herald-si/verificac19-sdk-php#95]
Risultato verifica:  [certificateStatus] => NOT_EU_DCC
per certificato valido.
Lo stesso certificato in debug mode viene validato correttamente.
Di seguito il debug della mia applicazione in debug_mode e in modalità standard acquisendo lo stesso certificato:

14:42:39 Herald\GreenPass\Model\CertificateSimple Object
(
    [person] => Herald\GreenPass\Model\SimplePerson Object
        (
            [standardizedFamilyName] => DISABLE-DEBUG-MODE-IN-PRODUCTION
            [familyName] => DISABLE-DEBUG-MODE-IN-PRODUCTION
            [standardisedGivenName] => DISABLE-DEBUG-MODE-IN-PRODUCTION
            [givenName] => DISABLE-DEBUG-MODE-IN-PRODUCTION
        )

    [dateOfBirth] => DateTimeImmutable Object
        (
            [date] => 1968-05-27 00:00:00.000000
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

    [certificateStatus] => VALID
    [timeStamp] => DateTimeImmutable Object
        (
            [date] => 2022-02-02 14:42:39.487618
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

)

14:42:39 DISABLE-DEBUG-MODE-IN-PRODUCTION DISABLE-DEBUG-MODE-IN-PRODUCTION - 1968-05-27
14:42:39 27/05/1968
14:42:39 VALIDO
14:42:39 IMPOSSIBILE ACCEDERE AL DB

14:42:58
14:42:58 Herald\GreenPass\Model\CertificateSimple Object
(
    [person] =>
    [dateOfBirth] =>
    [certificateStatus] => NOT_EU_DCC
    [timeStamp] => DateTimeImmutable Object
        (
            [date] => 2022-02-02 14:42:58.788733
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

)

14:42:58   -
14:42:58 //
14:42:58 NON VALIDO

**Comment by DevPGS** [comment]
esatto, la tipologia WORK funziona solamente con debug mode attiva, in quanto la funzionalità non è ancora stata approvata a livello di sdk android ufficiale del ministero e le specifiche potrebbero cambiare.
puoi vedere qui la PR relativa: https://github.com/herald-si/verificac19-sdk-php/pull/85

**Comment by DevPGS** [comment]
Lo stesso vale per la tipologia SCHOOL.
Appena le stesse saranno ufficializzate, verrà rilasciato l'aggiornamento per l'uso in produzione

**Comment by fvettore** [comment]
Non l'avevo capito...... volevo aggiornare i terminali, ma aspetterò.

Grazie 1000 per il vostro eccellente lavoro!!
