### ISSUE TITLE
modalità di scansione WORK, è funzionante?

### ISSUE THREAD

**Issue by st4nny** [herald-si/verificac19-sdk-php#98]
Buonsera,
ho testato l'ultima rel (1.4.3) con le nuove modalità di scansione, con quella work ottengo su tutti quelli testati:
certificateStatus: NOT_EU_DCC
person e dateOfBirth NULL
è normale?

**Comment by DevPGS** [comment]
Hi @st4nny ,
per la tipologia WORK è ancora valido questo: https://github.com/herald-si/verificac19-sdk-php/issues/95#issuecomment-1028012262 , in quanto il rilascio v1.4.3 ha sbloccato solamente la modalità scuola (in modo da essere allineato con il rilascio v1.1.4 dell'sdk android), ovvero la modalità WORK funziona solo con debug mode attivo per permettere di eseguire i test di funzionalità.
Entro la data del 15/02 verrà rilasciata la nuova versione di ministero-salute/it-dgc-verificac19-sdk-android e la libreria php si allineerà con quanto indicato.

A disposizione

**Comment by st4nny** [comment]
Carissimi,
grazie per l'approfondimento. Immaginavo una cosa del genere ma non avevo seguito lo scambio del thread indicato.

Un buon lavoro a voi.

**Comment by fvettore** [comment]
Ci sono previsioni per il rilascio?
Il 15/02 ormai è tra poche ore :)
(ho visto che la libreria del ministero non è ancora aggiornata...)

**Comment by DevPGS** [comment]
a livello codice sono state apportate le nuove (.....tante.....) modifiche per cambiamento delle regole in base a vaccini EMA/not_EMA allineando alla versione di 2 ore fa del ministero.
all'interno delle stesse è anche presente la nuova modalità WORK che fa più controlli rispetto alla precedente oltre che alla nuovissima scan mode ENTRY_ITALY.

* Ho già fatto il merge in develop della PR della "vecchia" WORK scanmode.
* Ho inoltre aperto una nuova PR con le modifiche qui sopra elencate, sto aspettando che venga chiusa quella sull'sdk ufficiale per eseguire il rilascio.
A quel punto eseguirò il merge in develop ed e rilascerò la nuova versione v1.5.0

**Comment by DevPGS** [comment]
rilascio effettuato ieri sera, fatemi sapere se riscontrate problemi.
Grazie a tutti
